language: node_js
node_js:
  - "4.1"

sudo: false
addons:
  postgresql: "9.4"

notifications:
  email: false

before_install:
  - npm install -g npm
  - npm config set loglevel info

before_script:
  - openssl genrsa -out server.rsa 2048
  - openssl rsa -in server.rsa -pubout > server.rsa.pub
  - psql -c 'create database travis_linkr;' -U postgres
  - export DATABASE_URL=postgres://postgres@localhost:5432/travis_linkr
  - npm install bower -g
  - bower install
  - export LINKR_USER=clux
  - export LINKR_EMAIL=h@x.io
  - export LINKR_PASSWORD=heythere
  - npm run setup
  - npm run build

after_script:
  - npm run coveralls
