language: node_js
node_js:
  - 0.10

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_linkr;' -U postgres
  - export DATABASE_URL=postgres://postgres@localhost:5432/travis_linkr
  - npm install bower -g
  - bower install
  - npm run build

notifications:
  email: true

after_script:
  - npm run coveralls
